# Machine Translation

In [122]:
import torch
import torch.nn as nn
import torch.optim

In [76]:
embeddings=torch.arange(2000).reshape(100,20)

In [113]:
embeddings[idx].shape

torch.Size([10, 3, 20])

In [114]:
A="c"
match A:
    case "c":
        print("a")

a


In [86]:
idx=idx.flatten()
idx

tensor([21, 49,  2, 36, 91, 77, 12, 86, 28, 87, 79, 60, 86, 22, 44,  2, 17, 53,
        22, 32, 79, 94, 57, 24, 19, 90, 99, 13, 28, 28])

In [115]:
X=[1,2,3,4,5,6]

In [123]:
?torch.optim.Adam

Init signature:
torch.optim.Adam(
    params: Union[collections.abc.Iterable[torch.Tensor], collections.abc.Iterable[dict[str, Any]], collections.abc.Iterable[tuple[str, torch.Tensor]]],
    lr: Union[float, torch.Tensor] = 0.001,
    betas: tuple[typing.Union[float, torch.Tensor], typing.Union[float, torch.Tensor]] = (0.9, 0.999),
    eps: float = 1e-08,
    weight_decay: float = 0,
    amsgrad: bool = False,
    *,
    foreach: Optional[bool] = None,
    maximize: bool = False,
    capturable: bool = False,
    differentiable: bool = False,
    fused: Optional[bool] = None,
    decoupled_weight_decay: bool = False,
)
Docstring:     
Implements Adam algorithm.

.. math::
   \begin{aligned}
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{input}      : \gamma \text{ (lr)}, \beta_1, \beta_2
            \text{ (betas)},\theta_0 \text{ (params)},f(\theta) \text{ (objective)}          \\
        &\hspace{13mm}      \lambda \te

[5, 6]

In [87]:
idx=idx.repeat(20,1).T
idx

tensor([[21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
         21, 21],
        [49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
         49, 49],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
          2,  2],
        [36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
         36, 36],
        [91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
         91, 91],
        [77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,
         77, 77],
        [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
         12, 12],
        [86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86,
         86, 86],
        [28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
         28, 28],
        [87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
         87, 87],
        [7

In [91]:
word_vectors=torch.gather(embeddings,0,idx)

In [102]:
word_vectors.reshape(10,-1)

tensor([[ 420,  421,  422,  423,  424,  425,  426,  427,  428,  429,  430,  431,
          432,  433,  434,  435,  436,  437,  438,  439,  980,  981,  982,  983,
          984,  985,  986,  987,  988,  989,  990,  991,  992,  993,  994,  995,
          996,  997,  998,  999,   40,   41,   42,   43,   44,   45,   46,   47,
           48,   49,   50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
        [ 720,  721,  722,  723,  724,  725,  726,  727,  728,  729,  730,  731,
          732,  733,  734,  735,  736,  737,  738,  739, 1820, 1821, 1822, 1823,
         1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835,
         1836, 1837, 1838, 1839, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547,
         1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559],
        [ 240,  241,  242,  243,  244,  245,  246,  247,  248,  249,  250,  251,
          252,  253,  254,  255,  256,  257,  258,  259, 1720, 1721, 1722, 1723,
         1724, 1725, 1726,

In [104]:
embeddings[49]

tensor([980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993,
        994, 995, 996, 997, 998, 999])